# NumPy Basics

#### Import numPy

In [2]:
import numpy as np

#### 1D array

In [8]:
# 1D array
my_list = [1, 2, 3];
arr_list = np.array(my_list);

In [12]:
# List of lists
my_mat = [[1, 2, 3], [4, 5, 3], [7, 4, 9]]
print(my_mat)

[[1, 2, 3], [4, 5, 3], [7, 4, 9]]


In [13]:
# 2D array
arr_mat = np.array(my_mat)
print(arr_mat)

[[1 2 3]
 [4 5 3]
 [7 4 9]]


In [15]:
# Get a range of numbers in an array
# Allnumbers from 0 to less than 20.
# Arguments - start, stop, step
print(np.arange(0, 20, 2))

[ 0  2  4  6  8 10 12 14 16 18]


In [20]:
# list of zeroes
np.zeros(5)
# list of ones
np.ones(3)

array([1., 1., 1.])

In [21]:
# Matrix of zeros
np.zeros((5,5))
# Matrix of ones
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Gives evenly spaced points in the range
# Arguments - start, stop (inclusive), nos of points
np.linspace(0, 20, 40)

array([ 0.        ,  0.51282051,  1.02564103,  1.53846154,  2.05128205,
        2.56410256,  3.07692308,  3.58974359,  4.1025641 ,  4.61538462,
        5.12820513,  5.64102564,  6.15384615,  6.66666667,  7.17948718,
        7.69230769,  8.20512821,  8.71794872,  9.23076923,  9.74358974,
       10.25641026, 10.76923077, 11.28205128, 11.79487179, 12.30769231,
       12.82051282, 13.33333333, 13.84615385, 14.35897436, 14.87179487,
       15.38461538, 15.8974359 , 16.41025641, 16.92307692, 17.43589744,
       17.94871795, 18.46153846, 18.97435897, 19.48717949, 20.        ])

#### Identity Matrix

In [23]:
# Get identity matrix of size
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
# Get list of random nos between 0 and 1, distributed uniformly
np.random.rand(5)
# Get array of random nos between 0 and 1, distributed uniformly
np.random.rand(7,7)

array([[0.98506291, 0.7751079 , 0.86267526, 0.31807462, 0.60600033,
        0.54504206, 0.87138326],
       [0.94965147, 0.88350737, 0.76920917, 0.38681288, 0.13282091,
        0.00744365, 0.7440292 ],
       [0.09032705, 0.00665746, 0.92496373, 0.01703533, 0.80231574,
        0.96764808, 0.66838228],
       [0.57012603, 0.4597916 , 0.34346673, 0.3394642 , 0.11900371,
        0.54170904, 0.40862223],
       [0.58278782, 0.52505843, 0.66553991, 0.92304924, 0.07527517,
        0.27887866, 0.84372416],
       [0.99148524, 0.43848034, 0.8770614 , 0.42797288, 0.87922189,
        0.3867121 , 0.00667332],
       [0.65644741, 0.54247596, 0.23445906, 0.42937294, 0.27989442,
        0.21008043, 0.02559042]])

In [26]:
# Get list of random integers from low to high(not inclusive)
# Arguments - low(start),high(end- not inclusive),nos of numbers wanted (optional, default - 1)
np.random.randint(0, 100, 5)

array([38, 36, 89, 32, 34])

#### Array as a matrix

In [30]:
# Reshape array
arr = np.arange(0, 9, 1)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Max/Min in array

In [32]:
# Max value in array
arr.max()
# Min value in array
arr.min()

0

In [34]:
# Get index of max value
arr.argmax()
# Get index of min value
arr.argmin()

0

In [36]:
# Get shape of structure
arr.shape

(9,)

In [38]:
# Get data type in array
arr.dtype

dtype('int64')

In [3]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
print(arr[8])

8


#### Array Slicing

In [5]:
print(arr[1:5])

[1 2 3 4]


In [6]:
# Get all elements from index 0 till before 7
print(arr[:7])

[0 1 2 3 4 5 6]


In [7]:
# Get all elements after index 2 to end
print(arr[2:])

[ 2  3  4  5  6  7  8  9 10]


In [8]:
# Slicing only gives reference to original array,
# and any changes made to this reference, will
# reflect in the original too. To fix this,
# and get a copy of array use this -
arr_copy = arr.copy()

#### 2D Arrays

In [11]:
# 2D arrays
arr_2d = np.array([[5, 10, 15], [15, 20, 25], [25, 30, 35]])
print(arr_2d)

[[ 5 10 15]
 [15 20 25]
 [25 30 35]]


In [12]:
# See entire row of matrix
arr_2d[2]

array([25, 30, 35])

In [13]:
# Get pieces out from a 2d array
arr_2d[:2, 1:]

array([[10, 15],
       [20, 25]])

In [14]:
arr = np.arange(1,11)
bool_arr = arr > 5
print(bool_arr)

[False False False False False  True  True  True  True  True]


In [15]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [17]:
# We can also use
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

#### Array Operations

In [ ]:
# Array addition/subtraction/multiplication element by element basis
arr + arr
# Add a scalar to every element
arr + 100

#### Array pre-built functions

In [23]:
# Square root of every element in arr
np.sqrt(arr)
# Max of arr
np.max(arr)
# Exponential of arr
np.exp(arr)
# Sin of all elements
np.sin(arr)

# For more check this out
# https://numpy.org/doc/stable/reference/routines.math.html

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [25]:
# Numpy Practice

# Numpy Practice

#### Create an array of 10 zeros 

In [27]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [28]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [33]:
arr = np.zeros(10)
arr += 5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [35]:
arr = np.linspace(10, 50, 41)
print(arr)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49. 50.]


#### Create an array of all the even integers from 10 to 50

In [41]:
arr = np.arange(10, 51, 2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [43]:
arr = np.arange(0, 9, 1).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [44]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1


In [46]:
np.random.rand(1)

array([0.0081682])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution


In [47]:
np.random.randn(25)

array([ 0.6222975 ,  1.71619248,  2.51845281, -1.60927044, -0.51909113,
       -1.27799891, -0.34521127,  0.773744  , -2.44725466,  0.71297355,
       -1.2214442 , -0.35547627,  0.42490695, -0.39342751, -1.60429419,
       -0.38610678, -1.06503807,  1.05504913,  1.24491612, -1.29768152,
        0.04301616, -0.47699913,  1.57019081, -0.37761303,  1.30602579])

#### Create the following matrix:

In [55]:
arr = np.arange(0.01, 1.01, .01).reshape(10, 10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [57]:
arr = np.linspace(0, 1, 20)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


#### Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [58]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [64]:
mat[3][4]

20

In [66]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [68]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [69]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [70]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [73]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

#### Get the sum of all the rows in mat

In [74]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

# DONE !